#!/bin/bash

pkill -f "kinopoisk_parser-0.0.1-SNAPSHOT.jar"
sleep 2
mvn clean install
java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=$DEBUG_IP:5005  -jar target/kinopoisk_parser-0.0.1-SNAPSHOT.jar | tee /proc/1/fd/1